### ISSUE TITLE
Error in meta-analysis of the b-lore package due to problem with array in python numpy package.

### ISSUE THREAD

**Issue by haukethomsen** [soedinglab/b-lore#2]
Running the example causes an error, that may be related to an update of the python numpy package.
/Users/hthomsen/Software/b-lore/example$ ./commands.sh 
Reading genotype from Locus.001.gen
Reading genotype from Locus.002.gen
Reading genotype from Locus.003.gen
Reading genotype from Locus.004.gen
Reading genotype from Locus.005.gen
Reading genotype from Locus.006.gen
Reading genotype from Locus.007.gen
Reading genotype from Locus.008.gen
Reading genotype from Locus.009.gen
Reading genotype from Locus.010.gen
Reading genotype from Locus.011.gen
Reading genotype from Locus.012.gen
Reading genotype from Locus.013.gen
Reading genotype from Locus.014.gen
Reading genotype from Locus.015.gen
Reading genotype from Locus.016.gen
Reading genotype from Locus.017.gen
Reading genotype from Locus.018.gen
Reading genotype from Locus.019.gen
Reading genotype from Locus.020.gen
Normalizing the genotype
Optimizing regularizer ...
RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =            3     M =           10

At X0         1 variables are exactly at the bounds

At iterate    0    f=  2.36330D+01    |proj g|=  4.63613D+01

At iterate    1    f= -9.91092D+00    |proj g|=  2.21722D+01

At iterate    2    f= -2.26100D+01    |proj g|=  6.40533D+00

At iterate    3    f= -2.40482D+01    |proj g|=  1.46197D+00

At iterate    4    f= -2.41373D+01    |proj g|=  1.68479D-01

At iterate    5    f= -2.41385D+01    |proj g|=  5.92494D-03

At iterate    6    f= -2.41385D+01    |proj g|=  2.61355D-05

At iterate    7    f= -2.41385D+01    |proj g|=  4.09665D-09

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
    3      7      8      7     0     1   4.097D-09  -2.414D+01
  F =  -24.138507542970395     

CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH             
RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =            3     M =           10

At X0         1 variables are exactly at the bounds

At iterate    0    f=  2.47694D+01    |proj g|=  4.67986D+01

At iterate    1    f= -9.17020D+00    |proj g|=  2.25348D+01

At iterate    2    f= -2.22608D+01    |proj g|=  6.54479D+00

At iterate    3    f= -2.37633D+01    |proj g|=  1.50868D+00

At iterate    4    f= -2.38585D+01    |proj g|=  1.77511D-01

At iterate    5    f= -2.38599D+01    |proj g|=  6.48271D-03

At iterate    6    f= -2.38599D+01    |proj g|=  3.04238D-05

At iterate    7    f= -2.38599D+01    |proj g|=  5.27255D-09

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
    3      7      8      7     0     1   5.273D-09  -2.386D+01
  F =  -23.859894886145504     

CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH             
RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =            3     M =           10

At X0         1 variables are exactly at the bounds

At iterate    0    f=  2.48224D+01    |proj g|=  4.68188D+01

At iterate    1    f= -9.13673D+00    |proj g|=  2.25533D+01

At iterate    2    f= -2.22474D+01    |proj g|=  6.54952D+00

At iterate    3    f= -2.37520D+01    |proj g|=  1.51023D+00

At iterate    4    f= -2.38474D+01    |proj g|=  1.77810D-01

At iterate    5    f= -2.38488D+01    |proj g|=  6.50181D-03

At iterate    6    f= -2.38488D+01    |proj g|=  3.05758D-05

At iterate    7    f= -2.38488D+01    |proj g|=  5.31645D-09

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
    3      7      8      7     0     1   5.316D-09  -2.385D+01
  F =  -23.848801722313514     

CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH             
Calculating summary statistics
Saving results
Reading genotype from Locus.001.gen
Reading genotype from Locus.002.gen
Reading genotype from Locus.003.gen
Reading genotype from Locus.004.gen
Reading genotype from Locus.005.gen
Reading genotype from Locus.006.gen
Reading genotype from Locus.007.gen
Reading genotype from Locus.008.gen
Reading genotype from Locus.009.gen
Reading genotype from Locus.010.gen
Reading genotype from Locus.011.gen
Reading genotype from Locus.012.gen
Reading genotype from Locus.013.gen
Reading genotype from Locus.014.gen
Reading genotype from Locus.015.gen
Reading genotype from Locus.016.gen
Reading genotype from Locus.017.gen
Reading genotype from Locus.018.gen
Reading genotype from Locus.019.gen
Reading genotype from Locus.020.gen
Normalizing the genotype
Optimizing regularizer ...
RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =            3     M =           10

At X0         1 variables are exactly at the bounds

At iterate    0    f=  1.72129D+01    |proj g|=  3.79120D+01

At iterate    1    f= -9.68694D+00    |proj g|=  1.69530D+01

At iterate    2    f= -1.81815D+01    |proj g|=  4.79390D+00

At iterate    3    f= -1.91251D+01    |proj g|=  1.24128D+00

At iterate    4    f= -1.92027D+01    |proj g|=  1.65880D-01

At iterate    5    f= -1.92042D+01    |proj g|=  7.57793D-03

At iterate    6    f= -1.92042D+01    |proj g|=  5.06227D-05

At iterate    7    f= -1.92042D+01    |proj g|=  1.56495D-08

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
    3      7      8      7     0     1   1.565D-08  -1.920D+01
  F =  -19.204165262659011     

CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH             
RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =            3     M =           10

At X0         1 variables are exactly at the bounds

At iterate    0    f=  1.63403D+01    |proj g|=  3.76925D+01

At iterate    1    f= -1.03767D+01    |proj g|=  1.68044D+01

At iterate    2    f= -1.87444D+01    |proj g|=  4.72604D+00

At iterate    3    f= -1.96600D+01    |proj g|=  1.20455D+00

At iterate    4    f= -1.97325D+01    |proj g|=  1.56138D-01

At iterate    5    f= -1.97338D+01    |proj g|=  6.75776D-03

At iterate    6    f= -1.97338D+01    |proj g|=  4.13006D-05

At iterate    7    f= -1.97338D+01    |proj g|=  1.10547D-08

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
    3      7      8      7     0     1   1.105D-08  -1.973D+01
  F =  -19.733814461573488     

CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH             
Calculating summary statistics
Saving results
Reading genotype from Locus.001.gen
Reading genotype from Locus.002.gen
Reading genotype from Locus.003.gen
Reading genotype from Locus.004.gen
Reading genotype from Locus.005.gen
Reading genotype from Locus.006.gen
Reading genotype from Locus.007.gen
Reading genotype from Locus.008.gen
Reading genotype from Locus.009.gen
Reading genotype from Locus.010.gen
Reading genotype from Locus.011.gen
Reading genotype from Locus.012.gen
Reading genotype from Locus.013.gen
Reading genotype from Locus.014.gen
Reading genotype from Locus.015.gen
Reading genotype from Locus.016.gen
Reading genotype from Locus.017.gen
Reading genotype from Locus.018.gen
Reading genotype from Locus.019.gen
Reading genotype from Locus.020.gen
Normalizing the genotype
Optimizing regularizer ...
RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =            3     M =           10

At X0         1 variables are exactly at the bounds

At iterate    0    f=  1.89894D+01    |proj g|=  3.92083D+01

At iterate    1    f= -8.63269D+00    |proj g|=  1.75115D+01

At iterate    2    f= -1.76821D+01    |proj g|=  5.62013D+00

At iterate    3    f= -1.89902D+01    |proj g|=  1.37658D+00

At iterate    4    f= -1.90855D+01    |proj g|=  1.78339D-01

At iterate    5    f= -1.90872D+01    |proj g|=  7.57564D-03

At iterate    6    f= -1.90872D+01    |proj g|=  4.58247D-05

At iterate    7    f= -1.90872D+01    |proj g|=  1.19326D-08

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
    3      7      8      7     0     1   1.193D-08  -1.909D+01
  F =  -19.087206851517539     

CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH             
RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =            3     M =           10

At X0         1 variables are exactly at the bounds

At iterate    0    f=  1.86681D+01    |proj g|=  3.94418D+01

At iterate    1    f= -9.12905D+00    |proj g|=  1.76233D+01

At iterate    2    f= -1.82289D+01    |proj g|=  5.61782D+00

At iterate    3    f= -1.95227D+01    |proj g|=  1.36455D+00

At iterate    4    f= -1.96151D+01    |proj g|=  1.73369D-01

At iterate    5    f= -1.96167D+01    |proj g|=  7.11998D-03

At iterate    6    f= -1.96167D+01    |proj g|=  4.07083D-05

At iterate    7    f= -1.96167D+01    |proj g|=  9.67987D-09

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
    3      7      8      7     0     1   9.680D-09  -1.962D+01
  F =  -19.616664488917287     

CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH             
Calculating summary statistics
Saving results
Reading summary statistics from output/pop1reg
Traceback (most recent call last):
  File "../bin/../blore/main.py", line 289, in <module>
    meta.optimize_hyperparameters(statdir, locusnamesfile, featurefiles, outdir, file_prefix, opts.zmax, opts.muvar, mparams)
  File "/Users/hthomsen/Software/b-lore/blore/meta.py", line 33, in optimize_hyperparameters
    summary_stat.combine()
  File "/Users/hthomsen/Software/b-lore/blore/inference/summary_stat.py", line 99, in combine
    summary.read()
  File "/Users/hthomsen/Software/b-lore/blore/iotools/io_summary.py", line 176, in read
    self._read_vmin()
  File "/Users/hthomsen/Software/b-lore/blore/iotools/io_summary.py", line 242, in _read_vmin
    self._precll = np.array(jaclist)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (20,) + inhomogeneous part.
/Users/hthomsen/Software/b-lore/example$

**Comment by banskt** [comment]
Thanks for creating this issue and also noting the source of the error. Fixed with a minor change.
